### Function Types and Hints

In [7]:
def hello_world(name : str) -> str:
    """
    Hello world message. 
    Args:
        name (str): User First Name.
    Returns:
        str: Message
    """
    
    ## try -> finally --> else | except

    try:
        hellotext = "Hello "+ name
    except:
        return "Invalid Input: name must be string."
    else:
        return hellotext
    finally:
        return "Hi!" 


In [8]:
hello_world("Bob") ##Hover

'Hi!'

### Context Managers -- Needs handel tasks like files and connections without manual input

In [ ]:
from contextlib import contextmanager
import time

@contextmanager
def timer(label:str):
    start = time.time()

    try:
        yield
    finally:
        end = time.time()
        print(f"{label} {end-start:.4f} seconds")


with timer("Calculate Sum"):
    total = sum(range(1, 10**9))
    print(f"Total: {total}")


#context managers

Total: 499999999500000000
Calculate Sum 14.2845 seconds


In [ ]:
class MyContextManager:
    def __init__(self):
        print('init method called') #1
        
    def __enter__(self):
        print('enter method called') #2
        return self
    
    def __exit__(self, exc_type, exc_value, exc_traceback):
        print('exit method called') #4

with MyContextManager() as manager:
    print('with statement block') #3

init method called
enter method called
with statement block
exit method called


## Iterables Genrators Comprehensions


Generators is used if you need a values to be accessed onece.

If storing the values are important List Comprehensions used.

Generator expression
(x*2 for x in range(256))

List comprehension
[x*2 for x in range(256)]

In [13]:
type(range(100).__iter__())

range_iterator

In [ ]:
import statistics

data = [1, 3, 3, 4, 7, 8, 8, 9]
data.sort()
median = statistics.median(data)
print(f"Median: {median}")


#Using Iterators
currentsum = 0
for i in range(len(data)):
    movingmedian = statistics.median(data[:i+1])
    print(f"Moving Median for {i} items {movingmedian:.4f}")


#Using Generators
def moving_median(data):
    """GENERATOR FUNCTION"""
    sorted_data = []
    for number in data:
        sorted_data.append(number)
        sorted_data.sort() 

        yield statistics.median(sorted_data) # generators

moving_median_value = moving_median(data)
print("\nMoving medians:")
for median in moving_median_value:
    print(median)



Median: 5.5
Moving Median for 0 items 1.0000
Moving Median for 1 items 2.0000
Moving Median for 2 items 3.0000
Moving Median for 3 items 3.0000
Moving Median for 4 items 3.0000
Moving Median for 5 items 3.5000
Moving Median for 6 items 4.0000
Moving Median for 7 items 5.5000

Moving medians:
1
2.0
3
3.0
3
3.5
4
5.5


In [26]:
####### Function override
# statics.median = moving_median(data)

mymedians = moving_median(data)
print(mymedians)

for m in mymedians:
    print(m)

print(mymedians) # nothing
for m in mymedians:
    print("Once Again", m) #Not called

<generator object moving_median at 0x00000171F440F760>
1
2.0
3
3.0
3
3.5
4
5.5
<generator object moving_median at 0x00000171F440F760>


# Numpy and Pandas

In [42]:
matA = [[1, 2, 3], [6, 9, 2], [4, 1, 5]]
matB = [[5, 7, 6], [8, 1, 4], [3, 2, 9]]


def matrixmultiplication(mA, mB):

    matAns = [[0 for _ in range(len(mB))] for _ in range(len(mA[0]))]
    for i in range(len(mA[0])):
        for j in range(len(mB)):
            indexvalue = 0
            for k in range(len(mA)):
                indexvalue += mA[i][k]*mB[k][j]

            matAns[i][j] = indexvalue
    
    return matAns

with timer("Manual Matrix Multiplication "):
    print(matrixmultiplication(matA, matB)) 
             


[[30, 15, 41], [108, 55, 90], [43, 39, 73]]
Manual Matrix Multiplication  0.0005 seconds


In [48]:
import numpy as np

matA = [[1, 2, 3], [6, 9, 2], [4, 1, 5]]
matB = [[5, 7, 6], [8, 1, 4], [3, 2, 9]]

npmatA = np.array(matA)
npmatB = np.array(matB)

with timer("Numpy Matrix Multiplication "):
    print(np.dot(matA, matB))

[[ 30  15  41]
 [108  55  90]
 [ 43  39  73]]
Numpy Matrix Multiplication  0.0002 seconds
